from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow , QProgressDialog , QMessageBox , QApplication
from PyQt5.QtCore import pyqtSlot , pyqtSignal , QLocale
from constants import RESULTS
from import_logging import get_logger
import sys

logger = get_logger(__name__)

# WARNING: Do not do any update in Ui_MainWindow class 
# Ui_MainWindow exacly copyd from .py file created by qt designer ( PyQt5 UI code generator 5.15.11)
# only change Ui_MainWindow in qt designer (create a versionN.ui )

# generated from reading ui file 'version5.ui' 
# +all extra are removed
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1059, 645)
        MainWindow.setWindowTitle("MainWindow")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_productName = QtWidgets.QLabel(self.centralwidget)
        self.label_productName.setGeometry(QtCore.QRect(70, 10, 631, 27))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_productName.setFont(font)
        self.label_productName.setText("Product")
        self.label_productName.setScaledContents(False)
        self.label_productName.setAlignment(QtCore.Qt.AlignCenter)
        self.label_productName.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.label_productName.setObjectName("label_productName")
        self.nextButton = QtWidgets.QPushButton(self.centralwidget)
        self.nextButton.setGeometry(QtCore.QRect(710, 540, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.nextButton.setFont(font)
        self.nextButton.setText("Next")
        self.nextButton.setObjectName("nextButton")
        self.backButton = QtWidgets.QPushButton(self.centralwidget)
        self.backButton.setGeometry(QtCore.QRect(600, 540, 75, 23))
        self.backButton.setFont(font)
        self.backButton.setText("Back")
        self.backButton.setObjectName("backButton")
        self.saveButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveButton.setGeometry(QtCore.QRect(220, 540, 75, 23))
        self.saveButton.setFont(font)
        self.saveButton.setText("save")
        self.saveButton.setObjectName("saveButton")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 90, 1041, 441))
        self.groupBox.setFont(font)
        self.groupBox.setTitle("PriceBox")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label_0 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_0.sizePolicy().hasHeightForWidth())
        self.label_0.setSizePolicy(sizePolicy)
        self.label_0.setMinimumSize(QtCore.QSize(200, 0))
        self.label_0.setFont(font)
        self.label_0.setText("اسپارک دیجی")
        self.label_0.setObjectName("label_0")
        self.gridLayout.addWidget(self.label_0, 0, 1, 1, 1)
        self.label_01 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_01.sizePolicy().hasHeightForWidth())
        self.label_01.setSizePolicy(sizePolicy)
        self.label_01.setMinimumSize(QtCore.QSize(100, 0))
        font.setPointSize(12)
        self.label_01.setFont(font)
        self.label_01.setText("شهر")
        self.label_01.setObjectName("label_01")
        self.gridLayout.addWidget(self.label_01, 0, 2, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.groupBox)
        self.label_32.setFont(font)
        self.label_32.setText("امتیاز / سال")
        self.label_32.setObjectName("label_32")
        self.gridLayout.addWidget(self.label_32, 8, 3, 1, 1)
        self.label_51 = QtWidgets.QLabel(self.groupBox)
        self.label_51.setFont(font)
        self.label_51.setText("شهر")
        self.label_51.setObjectName("label_51")
        self.gridLayout.addWidget(self.label_51, 12, 2, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.groupBox)
        self.label_42.setFont(font)
        self.label_42.setText("امتیاز / سال")
        self.label_42.setObjectName("label_42")
        self.gridLayout.addWidget(self.label_42, 10, 3, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setFont(font)
        self.label_11.setText("شهر")
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 3, 2, 1, 1)
        self.label_52 = QtWidgets.QLabel(self.groupBox)
        self.label_52.setFont(font)
        self.label_52.setText("امتیاز / سال")
        self.label_52.setObjectName("label_52")
        self.gridLayout.addWidget(self.label_52, 12, 3, 1, 1)
        self.label_02 = QtWidgets.QLabel(self.groupBox)
        self.label_02.setFont(font)
        self.label_02.setText("امتیاز / سال")
        self.label_02.setObjectName("label_02")
        self.gridLayout.addWidget(self.label_02, 0, 3, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.groupBox)
        font.setPointSize(14)
        self.label_40.setFont(font)
        self.label_40.setText("base price")
        self.label_40.setObjectName("label_40")
        self.gridLayout.addWidget(self.label_40, 10, 5, 1, 1)
        self.radioButton_5 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_5.setEnabled(True)
        self.radioButton_5.setFont(font)
        self.radioButton_5.setText("sujjested price")
        self.radioButton_5.setObjectName("radioButton_5")
        self.radioButtonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.radioButtonGroup.setObjectName("radioButtonGroup")
        self.radioButtonGroup.addButton(self.radioButton_5)
        self.gridLayout.addWidget(self.radioButton_5, 12, 6, 1, 1)
        self.label_60 = QtWidgets.QLabel(self.groupBox)
        self.label_60.setFont(font)
        self.label_60.setText("custom price")
        self.label_60.setObjectName("label_60")
        self.gridLayout.addWidget(self.label_60, 14, 5, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.groupBox)
        self.label_30.setFont(font)
        self.label_30.setText("base price")
        self.label_30.setObjectName("label_30")
        self.gridLayout.addWidget(self.label_30, 8, 5, 1, 1)
        self.radioButton_1 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_1.setFont(font)
        self.radioButton_1.setText("sujjested price")
        self.radioButton_1.setObjectName("radioButton_1")
        self.radioButtonGroup.addButton(self.radioButton_1)
        self.gridLayout.addWidget(self.radioButton_1, 3, 6, 1, 1)
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setText("sujjested price")
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButtonGroup.addButton(self.radioButton_2)
        self.gridLayout.addWidget(self.radioButton_2, 6, 6, 1, 1)
        self.radioButton_4 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_4.setFont(font)
        self.radioButton_4.setText("sujjested price")
        self.radioButton_4.setObjectName("radioButton_4")
        self.radioButtonGroup.addButton(self.radioButton_4)
        self.gridLayout.addWidget(self.radioButton_4, 10, 6, 1, 1)
        self.radioButton_0 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_0.setEnabled(True)
        self.radioButton_0.setFont(font)
        self.radioButton_0.setText("dont change price")
        self.radioButton_0.setCheckable(True)
        self.radioButton_0.setChecked(False)
        self.radioButton_0.setObjectName("radioButton_0")
        self.radioButtonGroup.addButton(self.radioButton_0)
        self.gridLayout.addWidget(self.radioButton_0, 0, 6, 1, 1)
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_3.setFont(font)
        self.radioButton_3.setText("sujjested price")
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButtonGroup.addButton(self.radioButton_3)
        self.gridLayout.addWidget(self.radioButton_3, 8, 6, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.groupBox)
        font.setPointSize(12)
        self.label_41.setFont(font)
        self.label_41.setText("شهر")
        self.label_41.setObjectName("label_41")
        self.gridLayout.addWidget(self.label_41, 10, 2, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.groupBox)
        self.label_31.setFont(font)
        self.label_31.setText("شهر")
        self.label_31.setObjectName("label_31")
        self.gridLayout.addWidget(self.label_31, 8, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setFont(font)
        self.label_12.setText("امتیاز / سال")
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 3, 3, 1, 1)
        self.label_50 = QtWidgets.QLabel(self.groupBox)
        self.label_50.setFont(font)
        self.label_50.setText("base price")
        self.label_50.setObjectName("label_50")
        self.gridLayout.addWidget(self.label_50, 12, 5, 1, 1)
        self.label_1 = QtWidgets.QLabel(self.groupBox)
        self.label_1.setFont(font)
        self.label_1.setText("اسپارک دیجی")
        self.label_1.setObjectName("label_1")
        self.gridLayout.addWidget(self.label_1, 3, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.groupBox)
        font.setPointSize(10)
        self.label_23.setFont(font)
        self.label_23.setText("اخرین اپدیت")
        self.label_23.setObjectName("label_23")
        self.gridLayout.addWidget(self.label_23, 6, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        self.label_13.setFont(font)
        self.label_13.setText("اخرین اپدیت")
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 3, 0, 1, 1)
        self.splitter = QtWidgets.QSplitter(self.groupBox)
        font.setPointSize(14)
        self.splitter.setFont(font)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.radioButton_6 = QtWidgets.QRadioButton(self.splitter)
        self.radioButton_6.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_6.sizePolicy().hasHeightForWidth())
        self.radioButton_6.setSizePolicy(sizePolicy)
        self.radioButton_6.setMaximumSize(QtCore.QSize(16, 16))
        self.radioButton_6.setFont(font)
        self.radioButton_6.setText("")
        self.radioButton_6.setObjectName("radioButton_6")
        self.radioButtonGroup.addButton(self.radioButton_6)
        self.spinBox = QtWidgets.QSpinBox(self.splitter)
        self.spinBox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox.sizePolicy().hasHeightForWidth())
        self.spinBox.setSizePolicy(sizePolicy)
        self.spinBox.setMinimumSize(QtCore.QSize(131, 20))
        self.spinBox.setMaximumSize(QtCore.QSize(131, 20))
        self.spinBox.setFont(font)
        self.spinBox.setMinimum(10000)
        self.spinBox.setMaximum(999999999)
        self.spinBox.setSingleStep(5000)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout.addWidget(self.splitter, 14, 6, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setFont(font)
        self.label_4.setText("اسپارک دیجی")
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 10, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setFont(font)
        self.label_3.setText("اسپارک دیجی")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 8, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setFont(font)
        self.label_5.setText("اسپارک دیجی")
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 12, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setFont(font)
        self.label_2.setText("اسپارک دیجی")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 6, 1, 1, 1)
        self.label_00 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_00.sizePolicy().hasHeightForWidth())
        self.label_00.setSizePolicy(sizePolicy)
        self.label_00.setMinimumSize(QtCore.QSize(180, 0))
        self.label_00.setFont(font)
        self.label_00.setText("old price")
        self.label_00.setObjectName("label_00")
        self.gridLayout.addWidget(self.label_00, 0, 5, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setFont(font)
        self.label_10.setText("base price")
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 3, 5, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.groupBox)
        self.label_20.setFont(font)
        self.label_20.setText("base price")
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 6, 5, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 4, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.groupBox)
        font.setPointSize(12)
        self.label_22.setFont(font)
        self.label_22.setText("امتیاز / سال")
        self.label_22.setObjectName("label_22")
        self.gridLayout.addWidget(self.label_22, 6, 3, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.groupBox)
        self.label_21.setFont(font)
        self.label_21.setText("شهر")
        self.label_21.setObjectName("label_21")
        self.gridLayout.addWidget(self.label_21, 6, 2, 1, 1)
        self.label_03 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_03.sizePolicy().hasHeightForWidth())
        self.label_03.setSizePolicy(sizePolicy)
        self.label_03.setMinimumSize(QtCore.QSize(140, 0))
        self.label_03.setFont(font)
        self.label_03.setText("اخرین اپدیت")
        self.label_03.setObjectName("label_03")
        self.gridLayout.addWidget(self.label_03, 0, 0, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.groupBox)
        font.setPointSize(10)
        self.label_33.setFont(font)
        self.label_33.setText("اخرین اپدیت")
        self.label_33.setObjectName("label_33")
        self.gridLayout.addWidget(self.label_33, 8, 0, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.groupBox)
        self.label_43.setFont(font)
        self.label_43.setText("اخرین اپدیت")
        self.label_43.setObjectName("label_43")
        self.gridLayout.addWidget(self.label_43, 10, 0, 1, 1)
        self.label_53 = QtWidgets.QLabel(self.groupBox)
        self.label_53.setFont(font)
        self.label_53.setText("اخرین اپدیت")
        self.label_53.setObjectName("label_53")
        self.gridLayout.addWidget(self.label_53, 12, 0, 1, 1)
        self.line_5 = QtWidgets.QFrame(self.groupBox)
        font.setPointSize(14)
        self.line_5.setFont(font)
        self.line_5.setMidLineWidth(1)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout.addWidget(self.line_5, 13, 0, 1, 7)
        self.line_4 = QtWidgets.QFrame(self.groupBox)
        self.line_4.setFont(font)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout.addWidget(self.line_4, 11, 0, 1, 7)
        self.line_3 = QtWidgets.QFrame(self.groupBox)
        self.line_3.setFont(font)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 9, 0, 1, 7)
        self.line_2 = QtWidgets.QFrame(self.groupBox)
        self.line_2.setFont(font)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 7, 0, 1, 7)
        self.line_1 = QtWidgets.QFrame(self.groupBox)
        self.line_1.setFont(font)
        self.line_1.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_1.setObjectName("line_1")
        self.gridLayout.addWidget(self.line_1, 4, 0, 1, 7)
        self.line_0 = QtWidgets.QFrame(self.groupBox)
        self.line_0.setFont(font)
        self.line_0.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_0.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_0.setObjectName("line_0")
        self.gridLayout.addWidget(self.line_0, 2, 0, 1, 7)
        self.label_productCount = QtWidgets.QLabel(self.centralwidget)
        self.label_productCount.setGeometry(QtCore.QRect(650, 60, 201, 20))
        self.label_productCount.setFont(font)
        self.label_productCount.setText("1/100")
        self.label_productCount.setScaledContents(False)
        self.label_productCount.setObjectName("label_productCount")
        self.label_url = QtWidgets.QLabel(self.centralwidget)
        self.label_url.setGeometry(QtCore.QRect(50, 60, 581, 21))
        self.label_url.setText("<a href=\"https://example.com\">https://example.com</a>")
        self.label_url.setTextFormat(QtCore.Qt.RichText)
        self.label_url.setOpenExternalLinks(True)
        self.label_url.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_url.setObjectName("label_url")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1059, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)



class MainApp(QMainWindow, Ui_MainWindow):
    _instance = None
    dataChanged = pyqtSignal(tuple)
    
    @classmethod
    def instance(cls):
        if cls._instance is None:
            cls._instance = cls()
        return cls._instance
    
    def __init__(self):
        if MainApp._instance is not None:
            raise RuntimeError("Use MainApp.instance() to get the singleton instance.")
        super().__init__()
        self.setupUi(self)
        self.__setup_connections()
        self.local = QLocale(QLocale.Persian)
        self.radioButton_6.toggled.connect(self.spinBox.setEnabled)
        self.spinBox.setEnabled(self.radioButton_6.isChecked())
        MainApp._instance = self 

    def __setup_connections(self):
        self.dataChanged.connect(self.update_table) 

    def set_len_list(self , give_me_len_list : int):
        self.len_list = give_me_len_list

    @pyqtSlot(tuple)
    def update_table(self ,tuple_of_dataIndex):
        data , index = tuple_of_dataIndex
        if data is None:
            logger.warning("No data to display.")
            return
        if not data.sites or len(data.sites) < RESULTS: 
            logger.error("Data sites are not properly populated.")
            logger.error(f"len data.sites = {len(data.sites)}")
            return
        
        self.label_productName.setText(data.name)
        if index < 0 :
            index = self.len_list+index
        self.label_productCount.setText(f"{index+1}/{self.len_list} → id={data.id}")
        self.label_url.setText(f'<a href="{data.torob_url}">{data.torob_url}</a>') 

        for i, site in enumerate(data.sites):  
            bg_color ="background-color: red;" if site.badged else "background-color: white;"
            if site.name == None :
                getattr(self, f"label_{i}").setText('')
                getattr(self, f"radioButton_{i}").setText('')
                getattr(self, f"radioButton_{i}").setEnabled(False)
            else :
                getattr(self, f"label_{i}").setText(site.name)
                if site.name == "اسپارک دیجی":
                    getattr(self, f"radioButton_{i}").setText(site.suggested_price)
                    bg_color ="background-color: green;"
                    dont_radio = i
                else :
                    getattr(self, f"radioButton_{i}").setText(self.local.toString(site.suggested_price))
                getattr(self, f"radioButton_{i}").setEnabled(True)
            getattr(self, f"label_{i}0").setText(self.local.toString(site.price))
            getattr(self, f"label_{i}1").setText(site.city)
            getattr(self, f"label_{i}2").setText(site.score_text)
            getattr(self, f"label_{i}3").setText(site.last_change)

            getattr(self, f"label_{i}").setStyleSheet(bg_color)
            getattr(self, f"label_{i}1").setStyleSheet(bg_color)
            getattr(self, f"label_{i}2").setStyleSheet(bg_color)
            getattr(self, f"label_{i}3").setStyleSheet(bg_color)
            getattr(self, f"label_{i}0").setStyleSheet(bg_color)
            getattr(self, f"radioButton_{i}").setStyleSheet(bg_color)

        try:
            self.spinBox.setValue(data.sites[0].suggested_price)
        except TypeError:
            try:
                self.spinBox.setValue(data.sites[1].suggested_price)
            except TypeError:
                pass
        self.__set_radio_checked(data,  dont_radio)

    def __set_radio_checked(self , data , dont_radio):
        chosen = data.chosen_site
        if chosen is None :
            getattr(self, f"radioButton_{dont_radio}").setChecked(True)
        else :
            logger.debug(f"checking radio_checked from data (ram) = {chosen} ")
            if isinstance(chosen, str): #radioButton_0...5
                getattr(self, "radioButton_"+chosen).setChecked(True)
            else : #radioButton_6
                self.radioButton_6.setChecked(True)
                self.spinBox.setValue(chosen)  


def critical_message(message):
    QMessageBox.critical(MainApp.instance(), "!!!", str(message))

class ProgressDialog(QProgressDialog):
    def __init__(self):
        mainApp = MainApp.instance()
        self.max = mainApp.len_list
        super().__init__("Updating products...", "Cancel", 0, self.max, mainApp)
        self.setWindowTitle("Please Wait")
        self.setWindowFlags(self.windowFlags() | QtCore.Qt.WindowStaysOnTopHint)
        self.setWindowModality(QtCore.Qt.WindowModal)
        self.setMinimumDuration(0)
        self.setAutoClose(True)
        self.setAutoReset(True)
    
    def progress(self ,i) -> bool :
        self.setLabelText(f"Updating item {i + 1} of {self.max}")
        self.setValue(i + 1)
        QApplication.processEvents()
        if self.wasCanceled():
            return True
        return False


    @pyqtSlot()
    def back_clicked(self):
        pass

    @pyqtSlot()
    def save_clicked(self):
        logger.info("Save button clicked!")

if __name__ == "__main__" :
    app = QApplication(sys.argv)
    window = MainApp()
    window.show()
    sys.exit(app.exec_())