from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow
from PyQt5.QtCore import pyqtSlot , pyqtSignal
from dataClass import Data
from dataClass import Site


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(877, 715)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 90, 841, 441))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter = QtWidgets.QSplitter(self.groupBox)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.radioButton_6 = QtWidgets.QRadioButton(self.splitter)
        self.radioButton_6.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_6.sizePolicy().hasHeightForWidth())
        self.radioButton_6.setSizePolicy(sizePolicy)
        self.radioButton_6.setMaximumSize(QtCore.QSize(16, 16))
        self.radioButton_6.setText("")
        self.radioButton_6.setObjectName("radioButton_6")
        self.spinBox = QtWidgets.QSpinBox(self.splitter)
        self.spinBox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox.sizePolicy().hasHeightForWidth())
        self.spinBox.setSizePolicy(sizePolicy)
        self.spinBox.setMinimumSize(QtCore.QSize(131, 20))
        self.spinBox.setMaximumSize(QtCore.QSize(131, 20))
        self.spinBox.setObjectName("spinBox")
        self.spinBox.setMaximum(999999999)  
        self.spinBox.setMinimum(10000)
        self.gridLayout.addWidget(self.splitter, 6, 3, 1, 1)
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_2.setObjectName("radioButton_2")
        self.gridLayout.addWidget(self.radioButton_2, 2, 3, 1, 1)
        self.radioButton_1 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_1.setObjectName("radioButton_1")
        self.gridLayout.addWidget(self.radioButton_1, 1, 3, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 1, 2, 1, 1)
        self.radioButton_4 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_4.setObjectName("radioButton_4")
        self.gridLayout.addWidget(self.radioButton_4, 4, 3, 1, 1)
        self.radioButton_5 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_5.setEnabled(True)
        self.radioButton_5.setObjectName("radioButton_5")
        self.gridLayout.addWidget(self.radioButton_5, 5, 3, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.groupBox)
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 2, 2, 1, 1)
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_3.setObjectName("radioButton_3")
        self.gridLayout.addWidget(self.radioButton_3, 3, 3, 1, 1)
        self.label_50 = QtWidgets.QLabel(self.groupBox)
        self.label_50.setObjectName("label_50")
        self.gridLayout.addWidget(self.label_50, 5, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label_1 = QtWidgets.QLabel(self.groupBox)
        self.label_1.setObjectName("label_1")
        self.gridLayout.addWidget(self.label_1, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.groupBox)
        self.label_40.setObjectName("label_40")
        self.gridLayout.addWidget(self.label_40, 4, 2, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.groupBox)
        self.label_30.setObjectName("label_30")
        self.gridLayout.addWidget(self.label_30, 3, 2, 1, 1)
        self.label_60 = QtWidgets.QLabel(self.groupBox)
        self.label_60.setObjectName("label_60")
        self.gridLayout.addWidget(self.label_60, 6, 2, 1, 1)
        self.label_00 = QtWidgets.QLabel(self.groupBox)
        self.label_00.setObjectName("label_00")
        self.gridLayout.addWidget(self.label_00, 0, 2, 1, 1)
        self.label_0 = QtWidgets.QLabel(self.groupBox)
        self.label_0.setObjectName("label_0")
        self.gridLayout.addWidget(self.label_0, 0, 0, 1, 1)
        self.radioButton_0 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_0.setEnabled(True)
        self.radioButton_0.setCheckable(True)
        self.radioButton_0.setChecked(False)
        self.radioButton_0.setObjectName("radioButton_0")
        self.gridLayout.addWidget(self.radioButton_0, 0, 3, 1, 1)
        self.label_productName = QtWidgets.QLabel(self.centralwidget)
        self.label_productName.setGeometry(QtCore.QRect(230, 50, 401, 20))
        self.label_productName.setTextFormat(QtCore.Qt.AutoText)
        self.label_productName.setScaledContents(False)
        self.label_productName.setAlignment(QtCore.Qt.AlignCenter)
        self.label_productName.setObjectName("label_productName")
        self.nextButton = QtWidgets.QPushButton(self.centralwidget)
        self.nextButton.setGeometry(QtCore.QRect(510, 540, 75, 23))
        self.nextButton.setObjectName("nextButton")
        self.backButton = QtWidgets.QPushButton(self.centralwidget)
        self.backButton.setGeometry(QtCore.QRect(430, 540, 75, 23))
        self.backButton.setObjectName("backButton")
        self.saveButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveButton.setGeometry(QtCore.QRect(290, 540, 75, 23))
        self.saveButton.setObjectName("saveButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 877, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        # Create a QButtonGroup for the radio buttons
        self.radioButtonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.radioButtonGroup.addButton(self.radioButton_1)
        self.radioButtonGroup.addButton(self.radioButton_2)
        self.radioButtonGroup.addButton(self.radioButton_3)
        self.radioButtonGroup.addButton(self.radioButton_4)
        self.radioButtonGroup.addButton(self.radioButton_5)
        self.radioButtonGroup.addButton(self.radioButton_6)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "PriceBox"))
        self.radioButton_2.setText(_translate("MainWindow", "sujjested price"))
        self.radioButton_1.setText(_translate("MainWindow", "sujjested price"))
        self.label_10.setText(_translate("MainWindow", "base price"))
        self.radioButton_4.setText(_translate("MainWindow", "sujjested price"))
        self.radioButton_5.setText(_translate("MainWindow", "sujjested price"))
        self.label_20.setText(_translate("MainWindow", "base price"))
        self.radioButton_3.setText(_translate("MainWindow", "sujjested price"))
        self.label_50.setText(_translate("MainWindow", "base price"))
        self.label_2.setText(_translate("MainWindow", "site name"))
        self.label_1.setText(_translate("MainWindow", "(buy box) site name"))
        self.label_3.setText(_translate("MainWindow", "site name"))
        self.label_4.setText(_translate("MainWindow", "site name"))
        self.label_5.setText(_translate("MainWindow", "site name"))
        self.label_40.setText(_translate("MainWindow", "base price"))
        self.label_30.setText(_translate("MainWindow", "base price"))
        self.label_60.setText(_translate("MainWindow", "custom price"))
        self.label_00.setText(_translate("MainWindow", "old price"))
        self.label_0.setText(_translate("MainWindow", "(this line may be first/middle/last  line) if spark : null "))
        self.radioButton_0.setText(_translate("MainWindow", "dont change price"))
        self.label_productName.setText(_translate("MainWindow", "Product"))
        self.nextButton.setText(_translate("MainWindow", "Next"))
        self.backButton.setText(_translate("MainWindow", "Back"))
        self.saveButton.setText(_translate("MainWindow", "save"))


class MainApp(QMainWindow, Ui_MainWindow):
    dataChanged = pyqtSignal(Data)
    def __init__(self):
        super().__init__()
        self.setupUi(self)
        self.setup_connections()

    def setup_connections(self):
        self.dataChanged.connect(self.update_table) 

    @pyqtSlot(Data)
    def update_table(self , data : Data):
        if data is None:
            print("No data to display.")
            return
        if not data.sites or len(data.sites) < 4:
            print("Error: Data sites are not properly populated.")
            return
        
        print(f"Updating UI with Data: {data.id}, Sites:")
        self.label_productName.setText(data.name)

        for i, site in enumerate(data.sites[:5]):  
            bg_color = "background-color: red;" if site.badged else "background-color: white;"
            getattr(self, f"label_{i+1}").setText(site.name)
            getattr(self, f"label_{i+1}0").setText(str(site.price))
            getattr(self, f"radioButton_{i+1}").setText(str(site.suggested_price))
            getattr(self, f"label_{i+1}").setStyleSheet(bg_color)
            getattr(self, f"label_{i+1}0").setStyleSheet(bg_color)
            getattr(self, f"radioButton_{i+1}").setStyleSheet(bg_color)

        self.spinBox.setValue(data.sites[0].suggested_price)
        self.spinBox.setSingleStep(5000)

    @pyqtSlot()
    def back_clicked(self):
        pass

    @pyqtSlot()
    def save_clicked(self):
        print("Save button clicked!")

if __name__ == "__main__" :
    import sys
    from PyQt5.QtWidgets import QApplication
    app = QApplication(sys.argv)
    window = MainApp()
    window.show()
    sys.exit(app.exec_())