# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'translate-3.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TranslateDialog(object):
    def setupUi(self, TranslateDialog):
        TranslateDialog.setObjectName("TranslateDialog")
        TranslateDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        TranslateDialog.resize(220, 457)
        TranslateDialog.setMinimumSize(QtCore.QSize(220, 0))
        TranslateDialog.setMaximumSize(QtCore.QSize(220, 16777215))
        TranslateDialog.setWindowTitle("ترجمه")
        TranslateDialog.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(TranslateDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget = QtWidgets.QTableWidget(TranslateDialog)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.AllEditTriggers)
        self.tableWidget.setRowCount(1)
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        item.setText("کد آسان")
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setText("ای دی سایت ")
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(90)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(True)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.tableWidget)
        QtCore.QMetaObject.connectSlotsByName(TranslateDialog)
        self.tableWidget.setSortingEnabled(True)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TranslateDialog = QtWidgets.QDialog()
    ui = Ui_TranslateDialog()
    ui.setupUi(TranslateDialog)
    TranslateDialog.show()
    sys.exit(app.exec_())
